### ISSUE TITLE
Could you add a license to this repo?

### ISSUE THREAD

**Issue by jiagaoxiang** [azzeddineCH/flash-nanoGPT#4]
Dear author,

Could you choose a license to your repo so that people can properly use your work? Thank you!

Context: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by azzeddineCH** [comment]
Thank you for your interest,  it's done

**Comment by jiagaoxiang** [comment]
Thank you!
